### ISSUE TITLE
simple example not working

### ISSUE THREAD

**Issue by fboerman** [luisza/djreservation#5]
Hi, 

I followed the docs and created a SimpleProductReservation with

        base_model = HardwareTarget     # required

        amount_field = 'quantity' # required

        max_amount_field = 'max_quantity'

        extra_display_field = [] # not required

however when i go to the view (as set in my urls.py with as_view I get KeyError 'pk'

I dont understand what im doing wrong, im following the docs and I want to create so there is no pk yet. why does it require one?

**Comment by luisza** [comment]
Hi, did you use SimpleProductReservation as base class? if does you need some url like 
```
urlpatterns = [
  ...
  url(r"^reservationroom/create/(?<pk>\d+)$", RoomReservation.as_view())
]
```
 why does it require one?
You need to know what product you want to reserve.

**Comment by albertalegria** [comment]
Hi Luis,
First of all thank you for releasing it as open source. I'll give it a try building a website for booking my apartment.

I'm totally new to django and I have a doubt. Following the installation instructions, when I arrived to the part where I have to run migrations, the following error appears after typing "python manage.py migrate":

`Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\xxx\...\Python\Python37-32\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\xxx\...\Python\Python37-32\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\xxx\...\Python\Python37-32\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\xxx\...\Python\Python37-32\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\xxx\...\Python\Python37-32\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\xxx\...\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\xxx\...\Python\Python37-32\lib\site-packages\djreservation\models.py", line 14, in <module>
    class Reservation(models.Model):
  File "C:\Users\xxx\...\Python\Python37-32\lib\site-packages\djreservation\models.py", line 29, in Reservation
    user = models.ForeignKey(auth_user)
TypeError: __init__() missing 1 required positional argument: 'on_delete'`

Do you know why?

Thanks,
Albert

**Comment by luisza** [comment]
Hi, Sorry you are using django 2.x , as requirement you need to add on_delete to all foreignkeys.
Djreservation was developed on django 1.11, and works well with it, but  django 2.0 is not supported jet, so you need to use django 1.11 that it's a extended supported version.

Maybe, I will include support to Django 2 on this days.

**Comment by albertalegria** [comment]
Hi! Thanks for your reply. My project doesn't need django 2.x, I can use 1.11.
If I finish the project I'll let you know.

Regards,
Albert

**Comment by dimaswidiantoro** [comment]
Thanks Luisza for the open source project, yes I definitely would love to see the app is supported by django 2.

**Comment by luisza** [comment]
Hi, I update to Django 2, also create a project  example.
